### ISSUE TITLE
Link CSS applied globally instead of just to the Menu

### ISSUE THREAD

**Issue by williamrmyers** [williamrmyers/New-CCSF-Website#1]
So the CSS text decorations are jacked up, and I havent figured out how to make the menu text decoration apply only to the Menu. So any other link on the site gets the menu text decoation.

**Comment by kevr** [comment]
Done. The links were specified globally, so I narrowed them down to links residing inside of #nav. Also, I added some boilerplate css for links in the pre body at the bottom of the page for edits down the road.
